org.schemaanalyst.sqlparser.UnsupportedSQLException: Unsupported SQL datatype [GSP EDataType: generic_t] at "release_year year", input line 109, column 5
	at org.schemaanalyst.sqlparser.DataTypeMapper.getDataType(DataTypeMapper.java:93)
	at org.schemaanalyst.sqlparser.SchemaMapper.mapColumn(SchemaMapper.java:88)
	at org.schemaanalyst.sqlparser.SchemaMapper.mapTable(SchemaMapper.java:73)
	at org.schemaanalyst.sqlparser.SchemaMapper.analyseStatement(SchemaMapper.java:51)
	at org.schemaanalyst.sqlparser.SchemaMapper.getSchema(SchemaMapper.java:42)
	at org.schemaanalyst.tool.GenerateConstraintCoverageData.task(GenerateConstraintCoverageData.java:62)
	at org.schemaanalyst.util.runner.Runner.doRun(Runner.java:139)
	at org.schemaanalyst.util.runner.Runner.run(Runner.java:117)
	at org.schemaanalyst.tool.GenerateConstraintCoverageData.main(GenerateConstraintCoverageData.java:88)
