/*************************************
 * Constraint coverage for UnixUsage *
 *************************************/
DROP TABLE IF EXISTS USAGE_HISTORY;
DROP TABLE IF EXISTS UNIX_COMMAND;
DROP TABLE IF EXISTS TRANSCRIPT;
DROP TABLE IF EXISTS USER_INFO;
DROP TABLE IF EXISTS RACE_INFO;
DROP TABLE IF EXISTS OFFICE_INFO;
DROP TABLE IF EXISTS COURSE_INFO;
DROP TABLE IF EXISTS DEPT_INFO;
CREATE TABLE DEPT_INFO (
	DEPT_ID	INT	PRIMARY KEY	NOT NULL,
	DEPT_NAME	VARCHAR(50)
);
CREATE TABLE COURSE_INFO (
	COURSE_ID	INT	PRIMARY KEY	NOT NULL,
	COURSE_NAME	VARCHAR(50),
	OFFERED_DEPT	INT	 REFERENCES DEPT_INFO (DEPT_ID),
	GRADUATE_LEVEL	SMALLINT
);
CREATE TABLE OFFICE_INFO (
	OFFICE_ID	INT	PRIMARY KEY	NOT NULL,
	OFFICE_NAME	VARCHAR(50),
	HAS_PRINTER	SMALLINT
);
CREATE TABLE RACE_INFO (
	RACE_CODE	INT	PRIMARY KEY	NOT NULL,
	RACE	VARCHAR(50)
);
CREATE TABLE USER_INFO (
	USER_ID	VARCHAR(50)	PRIMARY KEY	NOT NULL,
	FIRST_NAME	VARCHAR(50),
	LAST_NAME	VARCHAR(50),
	SEX	VARCHAR(1),
	DEPT_ID	INT	 REFERENCES DEPT_INFO (DEPT_ID),
	OFFICE_ID	INT	 REFERENCES OFFICE_INFO (OFFICE_ID),
	GRADUATE	SMALLINT,
	RACE	INT	 REFERENCES RACE_INFO (RACE_CODE),
	PASSWORD	VARCHAR(50)	NOT NULL,
	YEARS_USING_UNIX	INT,
	ENROLL_DATE	DATE
);
CREATE TABLE TRANSCRIPT (
	USER_ID	VARCHAR(50)	 REFERENCES USER_INFO (USER_ID)	NOT NULL,
	COURSE_ID	INT	 REFERENCES COURSE_INFO (COURSE_ID)	NOT NULL,
	SCORE	INT,
	PRIMARY KEY (USER_ID, COURSE_ID)
);
CREATE TABLE UNIX_COMMAND (
	UNIX_COMMAND	VARCHAR(50)	PRIMARY KEY	NOT NULL,
	CATEGORY	VARCHAR(50)
);
CREATE TABLE USAGE_HISTORY (
	USER_ID	VARCHAR(50)	 REFERENCES USER_INFO (USER_ID)	NOT NULL,
	SESSION_ID	INT,
	LINE_NO	INT,
	COMMAND_SEQ	INT,
	COMMAND	VARCHAR(50)
);
-- Coverage: 48/48 (100.00000%) 
-- Time to generate: 1979ms 

-- Satisfying all constraints
-- * Success: true
-- * Time: 531ms 
INSERT INTO DEPT_INFO(DEPT_ID, DEPT_NAME) VALUES(1, '');
INSERT INTO DEPT_INFO(DEPT_ID, DEPT_NAME) VALUES(0, '');
INSERT INTO COURSE_INFO(COURSE_ID, COURSE_NAME, OFFERED_DEPT, GRADUATE_LEVEL) VALUES(1, '', 0, 0);
INSERT INTO COURSE_INFO(COURSE_ID, COURSE_NAME, OFFERED_DEPT, GRADUATE_LEVEL) VALUES(0, '', 0, 0);
INSERT INTO OFFICE_INFO(OFFICE_ID, OFFICE_NAME, HAS_PRINTER) VALUES(1, '', 0);
INSERT INTO OFFICE_INFO(OFFICE_ID, OFFICE_NAME, HAS_PRINTER) VALUES(0, '', 0);
INSERT INTO RACE_INFO(RACE_CODE, RACE) VALUES(1, '');
INSERT INTO RACE_INFO(RACE_CODE, RACE) VALUES(0, '');
INSERT INTO USER_INFO(USER_ID, FIRST_NAME, LAST_NAME, SEX, DEPT_ID, OFFICE_ID, GRADUATE, RACE, PASSWORD, YEARS_USING_UNIX, ENROLL_DATE) VALUES('a', '', '', '', 0, 0, 0, 0, '', 0, '1000-01-01');
INSERT INTO USER_INFO(USER_ID, FIRST_NAME, LAST_NAME, SEX, DEPT_ID, OFFICE_ID, GRADUATE, RACE, PASSWORD, YEARS_USING_UNIX, ENROLL_DATE) VALUES('', '', '', '', 0, 0, 0, 0, '', 0, '1000-01-01');
INSERT INTO TRANSCRIPT(USER_ID, COURSE_ID, SCORE) VALUES('a', 0, 0);
INSERT INTO TRANSCRIPT(USER_ID, COURSE_ID, SCORE) VALUES('', 0, 0);
INSERT INTO UNIX_COMMAND(UNIX_COMMAND, CATEGORY) VALUES('a', '');
INSERT INTO UNIX_COMMAND(UNIX_COMMAND, CATEGORY) VALUES('', '');
INSERT INTO USAGE_HISTORY(USER_ID, SESSION_ID, LINE_NO, COMMAND_SEQ, COMMAND) VALUES('', 0, 0, 0, '');
INSERT INTO USAGE_HISTORY(USER_ID, SESSION_ID, LINE_NO, COMMAND_SEQ, COMMAND) VALUES('', 0, 0, 0, '');
-- * Number of objective function evaluations: 165
-- * Number of restarts: 0

-- Negating "PRIMARY KEY[DEPT_ID]" on table "DEPT_INFO"
-- * Success: true
-- * Time: 0ms 
INSERT INTO DEPT_INFO(DEPT_ID, DEPT_NAME) VALUES(0, '');
-- * Number of objective function evaluations: 1
-- * Number of restarts: 0

-- Negating "NOT NULL(DEPT_ID)" on table "DEPT_INFO"
-- * Success: true
-- * Time: 0ms 
INSERT INTO DEPT_INFO(DEPT_ID, DEPT_NAME) VALUES(NULL, '');
-- * Number of objective function evaluations: 2
-- * Number of restarts: 0

-- Negating "PRIMARY KEY[COURSE_ID]" on table "COURSE_INFO"
-- * Success: true
-- * Time: 1ms 
INSERT INTO DEPT_INFO(DEPT_ID, DEPT_NAME) VALUES(-1, '');
INSERT INTO COURSE_INFO(COURSE_ID, COURSE_NAME, OFFERED_DEPT, GRADUATE_LEVEL) VALUES(0, '', 0, 0);
-- * Number of objective function evaluations: 4
-- * Number of restarts: 0

-- Negating "FOREIGN KEY[OFFERED_DEPT]" on table "COURSE_INFO"
-- * Success: true
-- * Time: 14ms 
INSERT INTO DEPT_INFO(DEPT_ID, DEPT_NAME) VALUES(46, 'phctgpyae');
INSERT INTO COURSE_INFO(COURSE_ID, COURSE_NAME, OFFERED_DEPT, GRADUATE_LEVEL) VALUES(-38, 'danycpk', 55, 98);
-- * Number of objective function evaluations: 33
-- * Number of restarts: 1

-- Negating "NOT NULL(COURSE_ID)" on table "COURSE_INFO"
-- * Success: true
-- * Time: 25ms 
INSERT INTO DEPT_INFO(DEPT_ID, DEPT_NAME) VALUES(-3, 'yoaksyne');
INSERT INTO COURSE_INFO(COURSE_ID, COURSE_NAME, OFFERED_DEPT, GRADUATE_LEVEL) VALUES(NULL, 'rdlabiiv', NULL, 73);
-- * Number of objective function evaluations: 65
-- * Number of restarts: 1

-- Negating "PRIMARY KEY[OFFICE_ID]" on table "OFFICE_INFO"
-- * Success: true
-- * Time: 0ms 
INSERT INTO OFFICE_INFO(OFFICE_ID, OFFICE_NAME, HAS_PRINTER) VALUES(0, '', 0);
-- * Number of objective function evaluations: 1
-- * Number of restarts: 0

-- Negating "NOT NULL(OFFICE_ID)" on table "OFFICE_INFO"
-- * Success: true
-- * Time: 0ms 
INSERT INTO OFFICE_INFO(OFFICE_ID, OFFICE_NAME, HAS_PRINTER) VALUES(NULL, '', 0);
-- * Number of objective function evaluations: 2
-- * Number of restarts: 0

-- Negating "PRIMARY KEY[RACE_CODE]" on table "RACE_INFO"
-- * Success: true
-- * Time: 0ms 
INSERT INTO RACE_INFO(RACE_CODE, RACE) VALUES(0, '');
-- * Number of objective function evaluations: 1
-- * Number of restarts: 0

-- Negating "NOT NULL(RACE_CODE)" on table "RACE_INFO"
-- * Success: true
-- * Time: 0ms 
INSERT INTO RACE_INFO(RACE_CODE, RACE) VALUES(NULL, '');
-- * Number of objective function evaluations: 2
-- * Number of restarts: 0

-- Negating "PRIMARY KEY[USER_ID]" on table "USER_INFO"
-- * Success: true
-- * Time: 153ms 
INSERT INTO DEPT_INFO(DEPT_ID, DEPT_NAME) VALUES(22, 'hfckgxrbj');
INSERT INTO OFFICE_INFO(OFFICE_ID, OFFICE_NAME, HAS_PRINTER) VALUES(43, 'jvtywey', 44);
INSERT INTO RACE_INFO(RACE_CODE, RACE) VALUES(35, 'qicl');
INSERT INTO USER_INFO(USER_ID, FIRST_NAME, LAST_NAME, SEX, DEPT_ID, OFFICE_ID, GRADUATE, RACE, PASSWORD, YEARS_USING_UNIX, ENROLL_DATE) VALUES('', 'oojta', 'm', 'm', NULL, 43, 27, NULL, 'vbaic', 70, '1990-04-16');
-- * Number of objective function evaluations: 176
-- * Number of restarts: 1

-- Negating "FOREIGN KEY[DEPT_ID]" on table "USER_INFO"
-- * Success: true
-- * Time: 150ms 
INSERT INTO DEPT_INFO(DEPT_ID, DEPT_NAME) VALUES(83, 'xtndyifm');
INSERT INTO OFFICE_INFO(OFFICE_ID, OFFICE_NAME, HAS_PRINTER) VALUES(-67, 'lr', -36);
INSERT INTO RACE_INFO(RACE_CODE, RACE) VALUES(-98, 'tsmo');
INSERT INTO USER_INFO(USER_ID, FIRST_NAME, LAST_NAME, SEX, DEPT_ID, OFFICE_ID, GRADUATE, RACE, PASSWORD, YEARS_USING_UNIX, ENROLL_DATE) VALUES('b', 'ioo', 'whk', 'j', 36, -67, -31, NULL, 'omh', 8, '2019-07-01');
-- * Number of objective function evaluations: 195
-- * Number of restarts: 1

-- Negating "FOREIGN KEY[OFFICE_ID]" on table "USER_INFO"
-- * Success: true
-- * Time: 107ms 
INSERT INTO DEPT_INFO(DEPT_ID, DEPT_NAME) VALUES(37, 'hyhk');
INSERT INTO OFFICE_INFO(OFFICE_ID, OFFICE_NAME, HAS_PRINTER) VALUES(58, 'edrxhn', -65);
INSERT INTO RACE_INFO(RACE_CODE, RACE) VALUES(-78, 'tubgbpmei');
INSERT INTO USER_INFO(USER_ID, FIRST_NAME, LAST_NAME, SEX, DEPT_ID, OFFICE_ID, GRADUATE, RACE, PASSWORD, YEARS_USING_UNIX, ENROLL_DATE) VALUES('gehsbcwn', 's', 'b', 'y', NULL, 86, -99, NULL, 'gmxfwagq', -43, '1991-03-05');
-- * Number of objective function evaluations: 208
-- * Number of restarts: 1

-- Negating "FOREIGN KEY[RACE]" on table "USER_INFO"
-- * Success: true
-- * Time: 114ms 
INSERT INTO DEPT_INFO(DEPT_ID, DEPT_NAME) VALUES(20, 'nldfgawc');
INSERT INTO OFFICE_INFO(OFFICE_ID, OFFICE_NAME, HAS_PRINTER) VALUES(16, 'qligsfdx', 37);
INSERT INTO RACE_INFO(RACE_CODE, RACE) VALUES(83, 'ffudwkbs');
INSERT INTO USER_INFO(USER_ID, FIRST_NAME, LAST_NAME, SEX, DEPT_ID, OFFICE_ID, GRADUATE, RACE, PASSWORD, YEARS_USING_UNIX, ENROLL_DATE) VALUES('klunooja', 'ydyuvxnqt', 'nxrd', 'a', 22, NULL, 18, -74, '', -48, '2003-05-06');
-- * Number of objective function evaluations: 242
-- * Number of restarts: 1

-- Negating "NOT NULL(USER_ID)" on table "USER_INFO"
-- * Success: true
-- * Time: 99ms 
INSERT INTO DEPT_INFO(DEPT_ID, DEPT_NAME) VALUES(-60, 'jhwu');
INSERT INTO OFFICE_INFO(OFFICE_ID, OFFICE_NAME, HAS_PRINTER) VALUES(18, 'huqcx', 75);
INSERT INTO RACE_INFO(RACE_CODE, RACE) VALUES(70, 'itphsv');
INSERT INTO USER_INFO(USER_ID, FIRST_NAME, LAST_NAME, SEX, DEPT_ID, OFFICE_ID, GRADUATE, RACE, PASSWORD, YEARS_USING_UNIX, ENROLL_DATE) VALUES(NULL, 'uofwl', 'ubgv', 'd', -60, NULL, 45, NULL, 'tjdgga', -47, '1997-02-24');
-- * Number of objective function evaluations: 174
-- * Number of restarts: 1

-- Negating "NOT NULL(PASSWORD)" on table "USER_INFO"
-- * Success: true
-- * Time: 66ms 
INSERT INTO DEPT_INFO(DEPT_ID, DEPT_NAME) VALUES(92, 'peqasler');
INSERT INTO OFFICE_INFO(OFFICE_ID, OFFICE_NAME, HAS_PRINTER) VALUES(-26, 'fdu', -37);
INSERT INTO RACE_INFO(RACE_CODE, RACE) VALUES(7, 'ylkpgt');
INSERT INTO USER_INFO(USER_ID, FIRST_NAME, LAST_NAME, SEX, DEPT_ID, OFFICE_ID, GRADUATE, RACE, PASSWORD, YEARS_USING_UNIX, ENROLL_DATE) VALUES('ovqmkqae', 'lw', 'jbdnxa', 'u', NULL, -26, 94, NULL, NULL, -73, '2003-07-03');
-- * Number of objective function evaluations: 222
-- * Number of restarts: 1

-- Negating "PRIMARY KEY[USER_ID, COURSE_ID]" on table "TRANSCRIPT"
-- * Success: true
-- * Time: 180ms 
INSERT INTO DEPT_INFO(DEPT_ID, DEPT_NAME) VALUES(-88, 'eq');
INSERT INTO OFFICE_INFO(OFFICE_ID, OFFICE_NAME, HAS_PRINTER) VALUES(-47, 'vmo', -89);
INSERT INTO RACE_INFO(RACE_CODE, RACE) VALUES(18, 'qmvtq');
INSERT INTO USER_INFO(USER_ID, FIRST_NAME, LAST_NAME, SEX, DEPT_ID, OFFICE_ID, GRADUATE, RACE, PASSWORD, YEARS_USING_UNIX, ENROLL_DATE) VALUES('rkple', 'ug', 'aftki', 'b', NULL, NULL, -22, NULL, 'gaetogpgx', 25, '2017-08-15');
INSERT INTO COURSE_INFO(COURSE_ID, COURSE_NAME, OFFERED_DEPT, GRADUATE_LEVEL) VALUES(51, 'ylvlhrbhm', NULL, 16);
INSERT INTO TRANSCRIPT(USER_ID, COURSE_ID, SCORE) VALUES('a', 0, -43);
-- * Number of objective function evaluations: 614
-- * Number of restarts: 2

-- Negating "FOREIGN KEY[USER_ID]" on table "TRANSCRIPT"
-- * Success: true
-- * Time: 59ms 
INSERT INTO DEPT_INFO(DEPT_ID, DEPT_NAME) VALUES(-20, 'qdocrse');
INSERT INTO OFFICE_INFO(OFFICE_ID, OFFICE_NAME, HAS_PRINTER) VALUES(-99, 'q', 1);
INSERT INTO RACE_INFO(RACE_CODE, RACE) VALUES(68, 'usm');
INSERT INTO USER_INFO(USER_ID, FIRST_NAME, LAST_NAME, SEX, DEPT_ID, OFFICE_ID, GRADUATE, RACE, PASSWORD, YEARS_USING_UNIX, ENROLL_DATE) VALUES('w', 'plo', 'kf', 'p', -88, NULL, 82, NULL, 'owgvedrd', -11, '2004-06-03');
INSERT INTO COURSE_INFO(COURSE_ID, COURSE_NAME, OFFERED_DEPT, GRADUATE_LEVEL) VALUES(-36, 'd', NULL, -62);
INSERT INTO TRANSCRIPT(USER_ID, COURSE_ID, SCORE) VALUES('ngk', -36, -84);
-- * Number of objective function evaluations: 249
-- * Number of restarts: 1

-- Negating "FOREIGN KEY[COURSE_ID]" on table "TRANSCRIPT"
-- * Success: true
-- * Time: 53ms 
INSERT INTO DEPT_INFO(DEPT_ID, DEPT_NAME) VALUES(-79, 'yk');
INSERT INTO OFFICE_INFO(OFFICE_ID, OFFICE_NAME, HAS_PRINTER) VALUES(-5, 'lhabnv', 88);
INSERT INTO RACE_INFO(RACE_CODE, RACE) VALUES(-63, 'ujskugr');
INSERT INTO USER_INFO(USER_ID, FIRST_NAME, LAST_NAME, SEX, DEPT_ID, OFFICE_ID, GRADUATE, RACE, PASSWORD, YEARS_USING_UNIX, ENROLL_DATE) VALUES('ummopoqg', 'ykn', 'lkohdrgoi', 'm', NULL, NULL, -79, NULL, 'leumtd', 62, '2008-06-27');
INSERT INTO COURSE_INFO(COURSE_ID, COURSE_NAME, OFFERED_DEPT, GRADUATE_LEVEL) VALUES(35, 'cho', NULL, 42);
INSERT INTO TRANSCRIPT(USER_ID, COURSE_ID, SCORE) VALUES('', -42, -93);
-- * Number of objective function evaluations: 264
-- * Number of restarts: 1

-- Negating "NOT NULL(USER_ID)" on table "TRANSCRIPT"
-- * Success: true
-- * Time: 138ms 
INSERT INTO DEPT_INFO(DEPT_ID, DEPT_NAME) VALUES(93, 'nkdsfm');
INSERT INTO OFFICE_INFO(OFFICE_ID, OFFICE_NAME, HAS_PRINTER) VALUES(55, 'rmrhahd', 47);
INSERT INTO RACE_INFO(RACE_CODE, RACE) VALUES(81, 'afddnhhv');
INSERT INTO USER_INFO(USER_ID, FIRST_NAME, LAST_NAME, SEX, DEPT_ID, OFFICE_ID, GRADUATE, RACE, PASSWORD, YEARS_USING_UNIX, ENROLL_DATE) VALUES('co', 'stjok', 'gbmujvho', 'h', NULL, 18, -38, NULL, 'ewesulpky', -1, '2011-03-04');
INSERT INTO COURSE_INFO(COURSE_ID, COURSE_NAME, OFFERED_DEPT, GRADUATE_LEVEL) VALUES(-19, 'xklmshfp', NULL, -97);
INSERT INTO TRANSCRIPT(USER_ID, COURSE_ID, SCORE) VALUES(NULL, -19, -13);
-- * Number of objective function evaluations: 337
-- * Number of restarts: 1

-- Negating "NOT NULL(COURSE_ID)" on table "TRANSCRIPT"
-- * Success: true
-- * Time: 127ms 
INSERT INTO DEPT_INFO(DEPT_ID, DEPT_NAME) VALUES(-78, 'wqcu');
INSERT INTO OFFICE_INFO(OFFICE_ID, OFFICE_NAME, HAS_PRINTER) VALUES(17, 'laarwxcc', -20);
INSERT INTO RACE_INFO(RACE_CODE, RACE) VALUES(61, 'mlvpehtmu');
INSERT INTO USER_INFO(USER_ID, FIRST_NAME, LAST_NAME, SEX, DEPT_ID, OFFICE_ID, GRADUATE, RACE, PASSWORD, YEARS_USING_UNIX, ENROLL_DATE) VALUES('dnvsapjfi', 'hxxfdfmrq', 'cbpudodd', 'j', NULL, NULL, -19, 81, 'g', 54, '2012-04-20');
INSERT INTO COURSE_INFO(COURSE_ID, COURSE_NAME, OFFERED_DEPT, GRADUATE_LEVEL) VALUES(52, 'iu', NULL, -13);
INSERT INTO TRANSCRIPT(USER_ID, COURSE_ID, SCORE) VALUES('dnvsapjfi', NULL, 81);
-- * Number of objective function evaluations: 511
-- * Number of restarts: 1

-- Negating "PRIMARY KEY[UNIX_COMMAND]" on table "UNIX_COMMAND"
-- * Success: true
-- * Time: 0ms 
INSERT INTO UNIX_COMMAND(UNIX_COMMAND, CATEGORY) VALUES('', '');
-- * Number of objective function evaluations: 1
-- * Number of restarts: 0

-- Negating "NOT NULL(UNIX_COMMAND)" on table "UNIX_COMMAND"
-- * Success: true
-- * Time: 0ms 
INSERT INTO UNIX_COMMAND(UNIX_COMMAND, CATEGORY) VALUES(NULL, '');
-- * Number of objective function evaluations: 2
-- * Number of restarts: 0

-- Negating "FOREIGN KEY[USER_ID]" on table "USAGE_HISTORY"
-- * Success: true
-- * Time: 61ms 
INSERT INTO DEPT_INFO(DEPT_ID, DEPT_NAME) VALUES(-77, 'eqriwh');
INSERT INTO OFFICE_INFO(OFFICE_ID, OFFICE_NAME, HAS_PRINTER) VALUES(-100, 'nhmywbu', 33);
INSERT INTO RACE_INFO(RACE_CODE, RACE) VALUES(-99, 'csrxr');
INSERT INTO USER_INFO(USER_ID, FIRST_NAME, LAST_NAME, SEX, DEPT_ID, OFFICE_ID, GRADUATE, RACE, PASSWORD, YEARS_USING_UNIX, ENROLL_DATE) VALUES('in', 'j', 'hr', 'i', 92, NULL, -78, NULL, 'wdxhcq', -36, '2004-09-22');
INSERT INTO USAGE_HISTORY(USER_ID, SESSION_ID, LINE_NO, COMMAND_SEQ, COMMAND) VALUES('b', 76, 99, 69, 'luu');
-- * Number of objective function evaluations: 267
-- * Number of restarts: 1

-- Negating "NOT NULL(USER_ID)" on table "USAGE_HISTORY"
-- * Success: true
-- * Time: 101ms 
INSERT INTO DEPT_INFO(DEPT_ID, DEPT_NAME) VALUES(-35, 'anndy');
INSERT INTO OFFICE_INFO(OFFICE_ID, OFFICE_NAME, HAS_PRINTER) VALUES(-58, 'idmh', -34);
INSERT INTO RACE_INFO(RACE_CODE, RACE) VALUES(-94, 'cmdpyuc');
INSERT INTO USER_INFO(USER_ID, FIRST_NAME, LAST_NAME, SEX, DEPT_ID, OFFICE_ID, GRADUATE, RACE, PASSWORD, YEARS_USING_UNIX, ENROLL_DATE) VALUES('ayvs', 'vchxxje', 'ddfbiia', 'u', NULL, NULL, 43, NULL, 't', -65, '1998-08-05');
INSERT INTO USAGE_HISTORY(USER_ID, SESSION_ID, LINE_NO, COMMAND_SEQ, COMMAND) VALUES(NULL, 58, 25, -65, 'tajcqin');
-- * Number of objective function evaluations: 259
-- * Number of restarts: 1

